### ISSUE TITLE
Issue Running Example Scenes - No Output or Errors

### ISSUE THREAD

**Issue by marianomeijome** [SpectacularAI/unity-wrapper#2]
I'm having trouble getting any sort of feedback / results from the example scenes. The only scene that produced results was the Recording scene. I checked out the recorded videos and they looked right.

At first I had an issue related to OAK-D calibration, but once successfully calibrated, I no longer get anything in the console. I've confirmed the device works as expected in the DepthAI Viewer. 

Each scene I run makes the Windows sound of device disconnected/connected, but I'm not seeing anything in the unity console, scene, or game view reacting to moving the device. Let me know if there's any additional info I can provide. Thanks for any help!

> Original OAK-D Device from Kickstarter

> Unity 2022.3.47f1

> Windows 10

**Comment by kaatrasa** [comment]
Hey,

Could you try if our python examples work with your device? If you have Python installed, you can simply run
`pip install spectacularai[full]`

Then you can record a dataset (with live preview):
`sai-cli record oak`
![image](https://github.com/user-attachments/assets/91ac8098-ea76-48d7-aa0c-b377d61afe05)

The recording should have these files:
```
data.mkv    
data2.mkv  
data3.mkv        
data.jsonl  
rgb_video.mp4
vio_config.yaml       
calibration.json
```

**Comment by marianomeijome** [comment]
Thanks for the help! The first time running `sai-cli record oak` let me know that my IMU firmware needed updated:

> [14442C1051D0A1D000] [4.1] [7.377] [IMU(0)] [critical] IMU firmware version detected: 3.2.13 is not supported. Latest supported: 3.9.9. Use 'imu.enableFirmwareUpdate(True)' once to update firmware to latest.

I ran `imu_firmware_update.py` from depthai-python repo and now it's working as expected along with the Unity examples. 

Thank you!
